### ISSUE TITLE
Errors encountered during 6.6.2-0-x13s+ initramfs build on x13s-archiso from 8.03.2023 

### ISSUE THREAD

**Issue by electronarchy** [ironrobin/x13s-alarm#11]
![PXL_20231124_201446426](https://github.com/ironrobin/x13s-alarm/assets/133607109/241f09bd-0eb5-4253-86b1-50a96a197a8b)

arch-chrooted into the system, `mkinitramfs -P` always returns errors on the x13s kernel

tried getting a verbose output, nothing is clarified why it's incomplete. system boot cycles with grub. using all the bootflags listed in the readme

i also tried to pacstrap the x13s kernel and same result

i dont think i'm doing anything wrong... wondering if this is an issue with the latest x13s-archiso and new x13s firmware (UEFI from Lenovo), or the kernel package itself. but i have reproduced multiple times and cant get this thing to boot!

**Comment by theironrobin** [comment]
I get the same thing. you can ignore those warnings. If you are having issues booting i would take a look at the eos tutorial which you can use as a guide to get things up and running. https://github.com/ironrobin/archiso-x13s/wiki/EndeavourOS-Tutorial

If you need continued support getting things booting, then you can join the aarch64-laptops matrix channel. https://matrix.to/#/#_oftc_#aarch64-laptops:matrix.org
