### ISSUE TITLE
Repo currently broken

### ISSUE THREAD

**Issue by caljorden** [ironrobin/x13s-alarm#13]
Hello,

First, I want to thank you for your work on this repo.  I greatly appreciate being able to use this to run Arch Linux on my x13s.

However, as of 12:30pm UTC on Monday, March 18th, 2024 - this repo is not functioning.  The package list seems to indicate that a Linux kernel release 6.8.1 should be available, but no such file(s) exist (at least the -headers download is not working, and I don't see the non-suffixed 6.8.1 kernel file either).

I don't want to bother you, but I thought I would call this to your attention.

Here is what I am seeing:

```
[root@x13s ~]# pacman -Syu
:: Synchronizing package databases...
 ironrobin-x13s is up to date
 core is up to date
 extra is up to date
 alarm is up to date
 aur is up to date
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Packages (50) alsa-card-profiles-1:1.0.4-1  aom-3.8.2-1  archlinux-keyring-20240313-1  at-spi2-core-2.50.2-1  bluez-5.73-4
              bluez-libs-5.73-4  ca-certificates-mozilla-3.99-1  chromium-123.0.6312.46-1  e2fsprogs-1.47.0-2  eog-45.3-1  expat-2.6.2-1
              folks-0.15.8-1  ghostscript-10.03.0-2  gnome-control-center-45.3-2  gnome-online-accounts-3.48.1-1  gnome-shell-1:45.5-1
              gtkmm3-3.24.9-1  harfbuzz-8.3.1-1  harfbuzz-icu-8.3.1-1  iana-etc-20240222-1  icu-74.2-2  libgoa-3.48.1-1  libldap-2.6.7-1
              libopenmpt-0.7.5-1  libpipewire-1:1.0.4-1  librsvg-2:2.57.3-1  libva-2.21.0-1  libxml2-2.12.6-1  linux-x13s-6.8.1-1
              linux-x13s-headers-6.8.1-1  meson-1.4.0-2  mkinitcpio-38.1-1  net-snmp-5.9.4-2  nss-3.99-1  ostree-2024.5-1  pacman-6.1.0-3
              pcre2-10.43-1  pipewire-1:1.0.4-1  pipewire-audio-1:1.0.4-1  pipewire-jack-1:1.0.4-1  pkgconf-2.1.1-1  procps-ng-4.0.4-3
              python-pydantic-2.6.4-1  python-wheel-0.43.0-1  qt5-base-5.15.13+kde+r138-1  qt5-translations-5.15.13-1  run-parts-5.17-1
              sane-1.3.0-2  sqlite-3.45.2-1  waybar-0.10.0-1

Total Download Size:    324.61 MiB
Total Installed Size:  1148.81 MiB
Net Upgrade Size:       119.98 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 linux-x13s-headers-6.8.1-1-aarch64.pkg.tar.xz failed to download
 Total ( 1/50)                                           324.6 MiB  1002 MiB/s 00:00 [################################################] 100%
error: failed retrieving file 'linux-x13s-headers-6.8.1-1-aarch64.pkg.tar.xz' from github.com : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed to commit transaction (failed to retrieve some files)
Errors occurred, no packages were upgraded.

```

Warm Regards!

**Comment by alex-startengine** [comment]
@caljorden thank you for reporting. I am had some issues with 6.8 so i took it out of the repo manually, which might have cause things to because out of sync. please bear with me while i work through the issues with the new kernel

**Comment by theironrobin** [comment]
@caljorden Thanks for the report. The repo is out of sync  right now because I uploaded 6.8 but found a critical issue in it, so i manually removed it. Bear with me as a work to solve the issue.

**Comment by caljorden** [comment]
Thanks for the update, please feel free to close this issue as you are aware of the problem.

**Comment by theironrobin** [comment]
@caljorden repo should be fixed. had to roll back from 6.8 but at least we have 6.7.10 now.

**Comment by caljorden** [comment]
@theironrobin I am now able to perform a full upgrade, and the 6.7.10 kernel is running well.  Thanks again for all of your work on this!
