### ISSUE TITLE
Current Kernel Configuration is too sparse

### ISSUE THREAD

**Issue by masmullin2000** [ironrobin/x13s-alarm#16]
Johan's defconfig is too sparse for normal usage.

See: https://github.com/ironrobin/x13s-alarm/pull/15

For my suggestions on how to address.

**Comment by theironrobin** [comment]
first of all, i apologize that the update broke your system. we used to carry the laptop_defconfig which was less sparse, but upstream (steev) has stopped maintaining / carrying laptop_defconfig. 

this means that every time the kernel updates, especially major versions, a new config will need to be created with the typical distro options enabled. this is a lot of effort for me to do by hand. perhaps a shell script could be created that looks for the options and adds them if they are not enabled. what do you think?

**Comment by masmullin2000** [comment]
> first of all, i apologize that the update broke your system.

No worries.

I think a shell script will be really hard to do.  I'd suggest one of four options

1) Take jhovold's config, change the /etc/mkinicpio.conf file to add the required modules (https://github.com/jhovold/linux/commit/357c0f0c7ad2d7d95a3200b6cfd7bef43299de04)
```
MODULES=(nvme phy-qcom-qmp-pcie pcie-qcom phy-qcom-qmp-ufs ufs-qcom i2c-hid-of i2c-qcom-geni leds_qcom_lpg pwm_bl qrtr pmic_glink_altmode gpio_sbu_mux phy_qcom_qmp_combo gpucc_sc8280xp dispcc_sc8280xp phy_qcom_edp panel_edp msm)
```
And add some disclaimer to the readme that BTRFS/XFS/USB-devices will not work.  Perhaps point people to the patchset I posted https://github.com/ironrobin/x13s-alarm/pull/15 for people to create their own kernel.

PROS: running system for users.  Very little extra work required.

CONS: Bad user experience for people who aren't able to create their own kernel.

2) Apply the patchset I posted, in the PKGBUILD add a `make olddefconfig` between lines 62 and 63

PROS: better user experience than option 1.

CONS: You'll need to maintain patchsets as other people will request more features, divergence from jhovold's `johan_defconfig` as he adds new features.

3) Use the last known good .config file from steev.  Insert the make olddefconfig between 62 and 63 in PKGBUILD

PROS & CONS: essentially the same as option 2, but users will have "more stuff"  Compilation takes longer.

4) Have a list of individual patches (eg each commit I added for the MR #15 would be an individual patch file).  PKGBUILD would call `make johan_defconfig` then git apply each patch

PROS: up-to-date with jhovold's defconfig, more features for end users

CONS: possible merge conflicts as time goes making maintenance more difficult for you

RECOMMENDATION:

I suggest you take option 1, then allow people like me to pull some weight and provide a more feature rich kernel.

If you wouldn't mind providing me with some education materials on how I can create an arch package so that people could do something like `sudo pacman -S linux-x13s-mullin` like how they can do a `sudo pacman -S linux-x13s` right now.

**Comment by ThatWileyGuy** [comment]
For #1, couldn't the linux-x13s package just include a file in /etc/mkinitcpio.conf.d to add the needed modules to the MODULES array out of the box?

**Comment by theironrobin** [comment]
per @ThatWileyGuy , I have included modules with the latest kernel `linux-x13s-6.9.2-1`

**Comment by theironrobin** [comment]
@masmullin2000 I decided to make a script that can update the kernel as it comes in from upstream. https://github.com/ironrobin/x13s-alarm/blob/trunk/linux-x13s/patch_kernel_config.py for now i won't support things like app armor or selinux, but i have added much of your suggested config.
